accounts/urls.py
from django.urls import path

from .views import (
    account_interactions,
    basic_user_info,
    update_profile,
    user_account_action,
    user_detail,
    user_list,
)

urlpatterns = [
    path("users", user_list, name="user_list"),
    path("users/<str:username>", user_detail, name="user_detail"),
    path("update", update_profile, name="update"),
    path("peep/<str:username>", basic_user_info, name="peep"),
    path("action/<str:action>/<str:username>", user_account_action, name="follow_user"),
    path(
        "interactions/<str:interaction_type>/<str:username>",
        account_interactions,
        name="account_interactions",
    ),
]

base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("v1/accounts/", include("accounts.urls")),
    path("v1/", include("main.urls")),
    path("prerender/", include("prerender.urls")),
    path("v1/auth/", include("authentication.urls")),
]

if settings.ADMIN_ENABLED:
    urlpatterns += [
        path(f"{settings.ADMIN_URL}/", admin.site.urls),
    ]

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dj_waanverse_auth/urls.py
from django.urls import include, path

from .social_auth import urls as social_auth_urls
from .views import (
    DeactivateMfaView,
    enable_mfa,
    index,
    login_view,
    logout_view,
    mfa_login,
    mfa_status,
    refresh_token_view,
    regenerate_recovery_codes,
    resend_verification_email,
    reset_password,
    signup_view,
    user_info,
    verify_email,
    verify_mfa,
    verify_reset_password,
)

urlpatterns = [
    path("login", login_view, name="login"),
    path("token/refresh", refresh_token_view, name="refresh_token"),
    path("resend/email", resend_verification_email, name="resend_verification_email"),
    path("verify/email", verify_email, name="verify_email"),
    path("signup", signup_view, name="signup"),
    path("me", user_info, name="user_info"),
    path("mfa/activate", enable_mfa, name="activate_mfa"),
    path("mfa/verify", verify_mfa, name="verify_mfa"),
    path("mfa/status", mfa_status, name="mfa_status"),
    path("mfa/regenerate-codes", regenerate_recovery_codes, name="regenerate_codes"),
    path("mfa/deactivate", DeactivateMfaView.as_view(), name="deactivate_mfa"),
    path("logout", logout_view, name="logout"),
    path("mfa/login", mfa_login, name="mfa_login"),
    path("password/reset", reset_password, name="reset_password"),
    path("password/reset/new", verify_reset_password, name="verify_reset_password"),
    path("", index, name="index"),
    path("google/", include(social_auth_urls)),
]

accounts/models.py
import uuid

from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.contrib.humanize.templatetags.humanize import naturalday
from django.db import models
from django.templatetags.static import static
from django.urls import reverse


class AccountManager(BaseUserManager):
    def create_user(self, email, username, name=None, password=None, **extra_fields):
        if not email:
            raise ValueError("Please enter your email")
        if not username:
            raise ValueError("Please enter your username")
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, name=name, **extra_fields)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(
        self, username, email, name=None, password=None, **extra_fields
    ):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(email, username, name, password, **extra_fields)


class Badge(models.Model):
    name = models.CharField(max_length=255)
    badge_image = models.ImageField(upload_to="badges/")
    description = models.TextField()
    value = models.DecimalField(max_digits=10, decimal_places=1)
    image_hash = models.CharField(
        max_length=255, default="L02v:alCD4fRlCk[Z2Z28wf5HXaI"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    @property
    def image(self):
        if self.badge_image:
            return self.badge_image.url
        else:
            return None

    @property
    def added_on(self):
        return naturalday(self.created_at)

    @property
    def updated_on(self):
        return naturalday(self.updated_at)


class Account(AbstractBaseUser, PermissionsMixin):
    GENDER_OPTIONS = (
        ("male", "male"),
        ("female", "female"),
        ("other", "other"),
    )
    name = models.CharField(max_length=255, blank=True, null=True)
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(max_length=255, unique=True, verbose_name="Email")
    phone = models.CharField(max_length=12, null=True, blank=True, unique=True)
    gender = models.CharField(
        max_length=10, blank=True, null=True, choices=GENDER_OPTIONS
    )
    date_of_birth = models.DateField(blank=True, null=True)
    profile_image_url = models.URLField(blank=True, null=True)
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name="Date joined")
    last_login = models.DateTimeField(auto_now=True, verbose_name="Last login")
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    tagline = models.CharField(max_length=255, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    verified = models.BooleanField(default=False)
    verified_company = models.BooleanField(default=False)
    location = models.CharField(max_length=20, blank=True, null=True)
    badges = models.ManyToManyField(
        "Badge", blank=True
    )  # Assuming Badge is defined elsewhere
    profile_image_hash = models.CharField(
        max_length=255, default="LTL55tj[~qof?bfQIUj[j[fQM{ay"
    )
    username_last_update = models.DateTimeField(blank=True, null=True)
    last_location = models.CharField(max_length=255, blank=True, null=True)
    cover_image_url = models.URLField(blank=True, null=True)
    cover_image_hash = models.CharField(blank=True, null=True, max_length=200)
    google_account = models.BooleanField(default=False)
    website = models.URLField(blank=True, null=True)

    referral_code = models.CharField(max_length=255, blank=True, unique=True, null=True)
    referred_accounts = models.ManyToManyField("self", blank=True)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    objects = AccountManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.name or self.username

    def save(self, *args, **kwargs):
        if not self.referral_code:
            self.referral_code = self.generate_referral_code()
        super().save(*args, **kwargs)

    def generate_referral_code(self):
        """Generate a unique referral code."""
        code = None
        while not code or Account.objects.filter(referral_code=code).exists():
            code = str(uuid.uuid4()).replace("-", "")[
                :10
            ]  # Generate a 10-character unique code
        return code

    def get_short_name(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_staff

    def has_module_perms(self, app_label):
        return True

    def get_image(self):
        if self.profile_image_url:
            return self.profile_image_url
        else:
            return static("images/default.webp")

    def get_absolute_url(self):
        return reverse("account", kwargs={"username": self.username})

    def follow(self, user):
        """Follow a user."""
        if not self.is_following(user):
            if user != self:
                Follow.objects.create(follower=self, following=user)

    def unfollow(self, user):
        """Unfollow a user."""
        Follow.objects.filter(follower=self, following=user).delete()

    def is_following(self, user):
        """Check if the user is following another user."""
        return Follow.objects.filter(follower=self, following=user).exists()

    def get_following(self):
        """Get the list of users this user is following."""
        return Account.objects.filter(
            accounts_followers__follower=self
        )  # Updated related_name

    def get_followers(self):
        """Get the list of accounts following this account."""
        return Account.objects.filter(
            accounts_following__following=self
        )  # Updated related_name

    @property
    def is_verified_account(self):
        return self.verified or self.verified_company

    class Meta:
        ordering = ["-id"]


class Follow(models.Model):
    follower = models.ForeignKey(
        Account,
        related_name="accounts_following",  # Changed to avoid conflict with main app
        on_delete=models.CASCADE,
    )
    following = models.ForeignKey(
        Account,
        related_name="accounts_followers",  # Changed to avoid conflict with main app
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("follower", "following")

    def __str__(self):
        return f"{self.follower} follows {self.following}"

accounts/views.py
from django.shortcuts import get_object_or_404
from rest_framework import generics, status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response

from accounts.models import Account

from .serializers import (
    AccountSerializer,
    BasicAccountSerializer,
    UpdateProfileSerializer,
)


class UserList(generics.ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = BasicAccountSerializer
    pagination_class = None

    def get_queryset(self):
        username = self.request.query_params.get("username", None)

        if username:
            return Account.objects.filter(username__icontains=username)[:5]
        return Account.objects.none()


user_list = UserList.as_view()


class UserDetail(generics.RetrieveAPIView):
    permission_classes = [AllowAny]
    serializer_class = AccountSerializer
    queryset = Account.objects.all()
    lookup_field = "username"

    def get_serializer_context(self):
        """Add additional context to the serializer."""
        context = super().get_serializer_context()
        context.update({"request": self.request})
        return context


user_detail = UserDetail.as_view()


@api_view(["PATCH"])
@permission_classes([IsAuthenticated])
def update_profile(request):
    user = request.user
    try:
        account = Account.objects.get(username=user.username)
    except Account.DoesNotExist:
        return Response(
            {"detail": "Account not found."}, status=status.HTTP_404_NOT_FOUND
        )

    serializer = UpdateProfileSerializer(
        account, data=request.data, partial=True, context={"request": request}
    )
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=status.HTTP_200_OK)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(["GET"])
def basic_user_info(request, username):
    try:
        user = Account.objects.get(username=username)
        serializer = BasicAccountSerializer(user, context={"request": request})
        return Response(data=serializer.data, status=status.HTTP_200_OK)
    except Exception:
        return Response({"error": "User not found."}, status=status.HTTP_404_NOT_FOUND)


@api_view(["POST"])
def user_account_action(request, action, username):
    """Handle follow or unfollow action."""
    if not request.user.is_authenticated:
        return Response(
            {"error": "Authentication required."}, status=status.HTTP_401_UNAUTHORIZED
        )

    user_to_follow = get_object_or_404(Account, username=username)

    if action not in ["follow", "unfollow"]:
        return Response(
            {"error": "Invalid action."}, status=status.HTTP_400_BAD_REQUEST
        )

    try:
        if action == "follow":
            request.user.follow(user_to_follow)
        elif action == "unfollow":
            request.user.unfollow(user_to_follow)

        return Response(data={"action": action}, status=status.HTTP_200_OK)
    except Exception as e:
        return Response({"error": str(e)}, status=status.HTTP_400_BAD_REQUEST)


@api_view(["GET"])
def account_interactions(request, interaction_type, username):
    user_account = get_object_or_404(Account, username=username)

    if interaction_type not in ["following", "followers"]:
        return Response({"error": "Invalid type"}, status=status.HTTP_400_BAD_REQUEST)

    try:
        if interaction_type == "following":
            accounts = user_account.get_following()
        elif interaction_type == "followers":
            accounts = user_account.get_followers()

        serializer = BasicAccountSerializer(
            accounts, many=True, context={"request": request}
        )
        return Response(serializer.data, status=status.HTTP_200_OK)

    except Exception:
        return Response(
            {"error": "Something went wrong"}, status=status.HTTP_400_BAD_REQUEST
        )

templates/accounts/login.html
<c-layout>
    <form method="post">
        <header>
            <h1>Welcome back to Alloqet</h1>
        </header>
        <section>
            <label for="id_login_field">Username, email or phone number</label>
            <input type="text" name="login_field" id="id_login_field" aria-label="Username, email or phone" />
        </section>

        <section>
            <label for="id_password">Password</label>
            <input type="password" name="password" id="id_password" aria-label="Password" />
        </section>
        <section>
        <p>Don't have an account? <a href="{{ signup_url }}">Signup</a></p>
        </section>
        <section>
            <button type="submit" aria-label="Log in">Log in</button>
        </section>
    </form>
</c-layout>

templates/accounts/signup.html
{% load prerender%}

<c-layout>
    <c-slot name="head">
        <!-- Search Engine Structured Data for SEO -->
        <script type="application/ld+json">
            {
                "@context": "https://schema.org",
                "@type": "WebPage",
                "name": "{{title}}",
                "description": "{{description}}",
                "url": "{% render_url 'pre_signup' %}",
                "potentialAction": {
                    "@type": "RegisterAction",
                    "target": "{% render_url 'pre_signup' %}",
                    "name": "Create account"
                }
            }
        </script>
    </c-slot>

    <form method="post">
        <header>
            <h1>Join Alloqet Today</h1>
            <p>
                By signing up for Alloqet, you agree to our
                <a href="https://www.waanverse.com/policies/user-agreement/" target="_blank" rel="noopener noreferrer"> User Agreement </a>.
            </p>
        </header>

        <section>
            <label for="id_name">Name</label>
            <input type="text" name="name" id="id_name" aria-label="Full Name" required />
        </section>

        <section>
            <label for="id_gender">Gender</label>
            <div>
                <label>
                    <input type="radio" name="gender" value="male" aria-label="Male" required />
                    Male
                </label>
                <label>
                    <input type="radio" name="gender" value="female" aria-label="Female" required />
                    Female
                </label>
                <label>
                    <input type="radio" name="gender" value="other" aria-label="Other" required />
                    Other
                </label>
            </div>
        </section>

        <section>
            <label for="id_email">Email Address</label>
            <input type="email" name="email" id="id_email" aria-label="Email Address" required />
        </section>

        <section>
            <label for="id_username">Username</label>
            <input type="text" name="username" id="id_username" aria-label="Username" required />
        </section>

        <section>
            <label for="id_password1">Password</label>
            <input type="password" name="password1" id="id_password1" aria-label="Password" required />
        </section>

        <section>
            <label for="id_password2">Confirm Password</label>
            <input type="password" name="password2" id="id_password2" aria-label="Confirm Password" required />
        </section>

        <section>
            <p>Already have an account? <a href="{% render_url 'pre_login' %}">Log in</a></p>
        </section>

        <section>
            <button type="submit" aria-label="Sign Up">Sign Up</button>
        </section>
    </form>
</c-layout>